### ISSUE TITLE
libportmidi.a is missing from brew install

### ISSUE THREAD

**Issue by michaelaye** [halfbyte/portmidi#1]
pygame's configure is searching for .a files on the Mac, and brew usually creates them but not for portmidi. Can this be fixed? Or can I provide an option to brew to create the static .a library as well?

**Comment by halfbyte** [comment]
@michaelaye Sorry for the late reply, somehow this went below my radar (I'm a terrible open source guy). I believe you're looking for a change to https://github.com/Homebrew/homebrew/blob/master/Library/Formula/portmidi.rb, right? There's some stuff that's python dependent in there, so maybe your issue has been fixed already? Either way, this repo is about the ruby bindings for portmidi, which should have, at least as I am aware of, nothing to do with pygame?
